### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by Nut2ml** [greener-group/progres#6]
If you get errors following the readme installation process, you can try changing the **pytorch version 1.11 to 1.12.**
Like this : `conda install pytorch=1.11 faiss-cpu -c pytorch` to `conda install pytorch=1.12 faiss-cpu -c pytorch`
Maybe it can work, but I don't know if the modified pytorch version will cause any other errors.

**Comment by jgreener64** [comment]
PyTorch 1.12 and later versions should work as far as I know, provided they are compatible with the other dependencies.

What error did you run into with the readme installation process?

**Comment by Nut2ml** [comment]
> PyTorch 1.12 and later versions should work as far as I know, provided they are compatible with the other dependencies.
> 
> What error did you run into with the readme installation process?

Error like this, I changed the pytorch version to 1.12 and it worked:

Traceback (most recent call last):
  File "/anaconda3/envs/prog/bin/progres", line 102, in <module>
    main()
  File "/anaconda3/envs/prog/bin/progres", line 74, in main
    from progres import progres_search_print
  File "/anaconda3/envs/prog/lib/python3.9/site-packages/progres/__init__.py", line 1, in <module>
    from .progres import *
  File "/anaconda3/envs/prog/lib/python3.9/site-packages/progres/progres.py", line 8, in <module>
    from torch_scatter import scatter
  File "/anaconda3/envs/prog/lib/python3.9/site-packages/torch_scatter/__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "/anaconda3/envs/prog/lib/python3.9/site-packages/torch/_ops.py", line 220, in load_library
    ctypes.CDLL(path)
  File "/anaconda3/envs/prog/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /anaconda3/envs/prog/lib/python3.9/site-packages/torch_scatter/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs

**Comment by jgreener64** [comment]
Looks like a pytorch-scatter issue, thanks for reporting.

**Comment by lvclark** [comment]
Thanks, this is very helpful.  I had tried setting `pytorch-scatter=2.1.0` but that did not solve the issue.  (Really, they way that conda makes sure that packages have compatible versions, this is probably an issue with pytorch-scatter not having its dependencies set properly in the conda repo.)

**Comment by lvclark** [comment]
Actually I am still having problems.  I cannot use Anaconda because my organization does not have a license, and I am trying to build a Docker container to convert to an Apptainer image.

Here is my Dockerfile currently:

``` docker
ARG MINIFORGE_VERSION="24.7.1-2"
ARG CONDA_INSTALL_PATH="/pub/conda"
ARG CONDA_ENV_NAME="progres_env"
# Can change $PROGRES_DATA_DIR rather than remaking image, if used in a different assoc
ARG PERSISTENCE_DIR="/data/hps/assoc/private/mylab/progres_cache"

#progres is the official repo on pypi, can override with an alternative for testing
# e.g. git+https://github.com/xeniorn/progres.git@main
ARG PROGRES_REPO='progres' 

FROM debian:12 as build

ARG CONDA_INSTALL_PATH
ARG MINIFORGE_VERSION

RUN apt-get -y update \
    && apt-get -y install wget git \
    && apt-get -y autoclean

# This block is specific for my institution, since we need SSL certificates for connecting to the internet
RUN apt-get update && apt-get install -y ca-certificates
COPY *.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates

# Miniforge instead of Miniconda (we have no Anaconda license)
RUN wget --quiet \
    https://github.com/conda-forge/miniforge/releases/download/${MINIFORGE_VERSION}/Miniforge3-Linux-x86_64.sh \
    && bash Miniforge3-Linux-x86_64.sh -bfp ${CONDA_INSTALL_PATH} \
    && rm -f Miniforge3-Linux-x86_64.sh

ENV PATH="${CONDA_INSTALL_PATH}/bin:${PATH}"

ARG CONDA_ENV_NAME
ENV CONDA_ENV_NAME=${CONDA_ENV_NAME}

RUN . ${CONDA_INSTALL_PATH}/etc/profile.d/conda.sh \
    && mamba create --yes -n ${CONDA_ENV_NAME} python=3.9 -c conda-forge \
    && conda activate ${CONDA_ENV_NAME} \
    && pip install torch --index-url https://download.pytorch.org/whl/cu124 \
    && mamba install --yes faiss-gpu -c pytorch \
    && pip install pyg_lib torch-scatter -f https://data.pyg.org/whl/torch-2.4.0+cu124.html \
    && mamba clean --yes --all

# Install Stride directly in container since it is only on Anaconda, not conda-forge
RUN apt-get install -y build-essential gcc

RUN mkdir /opt/stride

WORKDIR /opt/stride

RUN wget https://webclu.bio.wzw.tum.de/stride/stride.tar.gz
RUN tar -zxf stride.tar.gz
RUN make
RUN mv stride /usr/local/bin/

ARG PROGRES_REPO

RUN . ${CONDA_INSTALL_PATH}/etc/profile.d/conda.sh \
    && conda activate ${CONDA_ENV_NAME} \
    && yes | pip install "${PROGRES_REPO}" \
    && pip cache purge

ARG PERSISTENCE_DIR
ENV PROGRES_DATA_DIR=${PERSISTENCE_DIR}

ARG RUN_SCRIPT="/pub/run.sh"
ENV PROGRES_RUN_SCRIPT=${RUN_SCRIPT}

COPY "docker_runner.sh" ${RUN_SCRIPT}
RUN chmod +rx ${RUN_SCRIPT}

ENTRYPOINT [ "/pub/run.sh" ]
```

When, using this container, I try:

``` bash
progres search \
--querylist /mnt/progres_docker/test_query_list.txt \
--targetdb af21org \
--fileformat pdb \
--device cuda
```

I get

```
OSError: /pub/conda/envs/progres_env/lib/python3.9/site-packages/torch_scatter/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSsb
```

For the block that installs Pytorch, I have also tried:

```
RUN . ${CONDA_INSTALL_PATH}/etc/profile.d/conda.sh \
    && mamba create --yes -n ${CONDA_ENV_NAME} python=3.9 -c conda-forge \
    && conda activate ${CONDA_ENV_NAME} \
    && mamba install --yes pytorch=1.11 faiss-cpu -c pytorch \
    && mamba install --yes pytorch-scatter pyg -c pyg \
    && mamba clean --yes --all
```

and

```
RUN . ${CONDA_INSTALL_PATH}/etc/profile.d/conda.sh \
    && mamba create --yes -n ${CONDA_ENV_NAME} python=3.9 -c conda-forge \
    && conda activate ${CONDA_ENV_NAME} \
    && mamba install --yes pytorch=1.12 faiss-cpu -c pytorch \
    && mamba install --yes pytorch-scatter pyg -c pyg \
    && mamba clean --yes --all
```

and 

```
RUN . ${CONDA_INSTALL_PATH}/etc/profile.d/conda.sh \
    && mamba create --yes -n ${CONDA_ENV_NAME} python=3.9 -c conda-forge \
    && conda activate ${CONDA_ENV_NAME} \
    && mamba install --yes pytorch faiss-cpu -c pytorch \
    && mamba install --yes pytorch-scatter pyg -c pyg \
    && mamba clean --yes --all
```

These give similar errors although the exact string for the "undefined symbol" varies.

**Comment by jgreener64** [comment]
Organisational requirements can be tough. I don't have much specific advice here. Try `--device cpu` if you haven't already. Also, if `import torch_scatter` errors you could try reporting on their repo.

Here are the exact versions working on my system, you could try specifying versions of the relevant packages explicitly during install:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
annotated-types           0.7.0                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
beartype                  0.18.5                   pypi_0    pypi
biopython                 1.84                     pypi_0    pypi
blas                      1.0                         mkl  
brotli-python             1.0.9            py39h6a678d5_7  
ca-certificates           2024.7.2             h06a4308_0  
certifi                   2024.7.4         py39h06a4308_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
cudatoolkit               11.3.1               h2bc3f7f_2  
decorator                 5.1.1                    pypi_0    pypi
einops                    0.7.0                    pypi_0    pypi
exceptiongroup            1.2.1                    pypi_0    pypi
executing                 2.0.1                    pypi_0    pypi
faiss-cpu                 1.8.0           py3.9_h9d89a2e_0_cpu    pytorch
filelock                  3.14.0                   pypi_0    pypi
fsspec                    2024.3.1                 pypi_0    pypi
idna                      3.4              py39h06a4308_0  
intel-openmp              2023.1.0         hdb19cb5_46306  
ipython                   8.18.1                   pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jinja2                    3.1.3            py39h06a4308_0  
joblib                    1.2.0            py39h06a4308_0  
ld_impl_linux-64          2.38                 h1181459_1  
libfaiss                  1.8.0            hf65b397_0_cpu    pytorch
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            11.2.0               h00389a5_1  
libgfortran5              11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
libuv                     1.44.2               h5eee18b_0  
markupsafe                2.1.3            py39h5eee18b_0  
matplotlib-inline         0.1.7                    pypi_0    pypi
mkl                       2023.1.0         h213fc3f_46344  
mkl-service               2.4.0            py39h5eee18b_1  
mkl_fft                   1.3.8            py39h5eee18b_0  
mkl_random                1.2.4            py39hdb19cb5_0  
mmtf-python               1.1.3                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
msgpack                   1.0.8                    pypi_0    pypi
natsort                   8.4.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
networkx                  3.2.1                    pypi_0    pypi
numpy                     1.26.4           py39h5f9d8c6_0  
numpy-base                1.26.4           py39hb5e798b_0  
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         8.9.2.26                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.4.127                 pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
openssl                   3.0.14               h5eee18b_0  
packaging                 23.2             py39h06a4308_0  
parso                     0.8.4                    pypi_0    pypi
pexpect                   4.9.0                    pypi_0    pypi
pip                       23.3.1           py39h06a4308_0  
progres                   0.2.4                     dev_0    <develop>
prompt-toolkit            3.0.43                   pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pydantic                  2.8.2                    pypi_0    pypi
pydantic-core             2.20.1                   pypi_0    pypi
pyg                       2.1.0           py39_torch_1.11.0_cu113    pyg
pygments                  2.17.2                   pypi_0    pypi
pyparsing                 3.0.9            py39h06a4308_0  
pysocks                   1.7.1            py39h06a4308_0  
python                    3.9.19               h955ad1f_0  
pytorch                   1.11.0          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
pytorch-cluster           1.6.0           py39_torch_1.11.0_cu113    pyg
pytorch-mutex             1.0                        cuda    pytorch
pytorch-scatter           2.0.9           py39_torch_1.11.0_cu113    pyg
pytorch-sparse            0.6.15          py39_torch_1.11.0_cu113    pyg
readline                  8.2                  h5eee18b_0  
requests                  2.31.0           py39h06a4308_1  
scikit-learn              1.3.0            py39h1128e8f_1  
scipy                     1.12.0           py39h5f9d8c6_0  
setuptools                68.2.2           py39h06a4308_0  
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
stack-data                0.6.3                    pypi_0    pypi
stride                    1.6.4                         1    kimlab
sympy                     1.12                     pypi_0    pypi
tbb                       2021.8.0             hdb19cb5_0  
threadpoolctl             2.2.0              pyh0d69192_0  
tk                        8.6.12               h1ccaba5_0  
torch                     2.3.0                    pypi_0    pypi
tqdm                      4.65.0           py39hb070fc8_0  
traitlets                 5.14.3                   pypi_0    pypi
triton                    2.3.0                    pypi_0    pypi
typing_extensions         4.9.0            py39h06a4308_1  
tzdata                    2024a                h04d1e81_0  
urllib3                   2.1.0            py39h06a4308_1  
wcwidth                   0.2.13                   pypi_0    pypi
wheel                     0.41.2           py39h06a4308_0  
xz                        5.4.6                h5eee18b_0  
zlib                      1.2.13               h5eee18b_0  
```

**Comment by lvclark** [comment]
Thanks for your help with this.  I used your version list to make a yaml file for the conda environment, and just try it directly on our system instead of in a container, and I'm still having the issue.  But I will continue to work on it.

**Comment by lvclark** [comment]
Ok.  Got this working on my system and am setting aside the container issue unless we are sure we want to incorporate Progres into our Nextflow workflow.  I followed the instructions on your README, except (1) I used mamba instead of conda, and (2) I did not specify a version for pytorch or any other package.  After it was installed and I confirmed that it was working, I exported the environment to a yaml file, which can be used to recreate the environment.

``` yaml
name: prog
channels:
  - kimlab
  - pyg
  - pytorch
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - aiohappyeyeballs=2.4.3=pyhd8ed1ab_0
  - aiohttp=3.10.10=py39h9399b63_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - blas=1.0=mkl
  - brotli-python=1.1.0=py39hf88036b_2
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.1=py39h15c3d72_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cpython=3.9.20=py39hd8ed1ab_1
  - cuda-cudart=12.4.99=hd3aeb46_0
  - cuda-cudart_linux-64=12.4.99=h59595ed_0
  - cuda-cupti=12.4.127=he02047a_2
  - cuda-libraries=12.4.0=ha770c72_0
  - cuda-nvrtc=12.4.99=hd3aeb46_0
  - cuda-nvtx=12.4.127=he02047a_2
  - cuda-opencl=12.4.99=h59595ed_0
  - cuda-runtime=12.4.0=ha804496_0
  - cuda-version=12.4=h3060b56_3
  - faiss-cpu=1.9.0=py3.9_hadc1362_0_cpu
  - filelock=3.16.1=pyhd8ed1ab_0
  - frozenlist=1.4.1=py39h8cd3c5a_1
  - fsspec=2024.9.0=pyhff2d567_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py39h7196dd7_2
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - ld_impl_linux-64=2.43=h712a8e2_1
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libcblas=3.9.0=7_ha36c22a_netlib
  - libcublas=12.4.2.65=hd3aeb46_0
  - libcufft=11.2.0.44=hd3aeb46_0
  - libcufile=1.9.0.20=hd3aeb46_0
  - libcurand=10.3.5.119=hd3aeb46_0
  - libcusolver=11.6.0.99=hd3aeb46_0
  - libcusparse=12.3.0.142=hd3aeb46_0
  - libfaiss=1.9.0=hf65b397_0_cpu
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - libhwloc=2.11.1=default_hecaa2ac_1000
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=7_ha36c22a_netlib
  - libnpp=12.2.5.2=hd3aeb46_0
  - libnsl=2.0.1=hd590300_0
  - libnvfatbin=12.4.99=hd3aeb46_0
  - libnvjitlink=12.4.99=hd3aeb46_0
  - libnvjpeg=12.3.1.89=h59595ed_0
  - libsqlite=3.46.1=hadc24fc_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=he7c6b58_4
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=3.0.1=py39h9399b63_1
  - mkl=2023.0.0=h84fe81f_26648
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_0
  - multidict=6.1.0=py39h9399b63_1
  - ncurses=6.5=he02047a_1
  - networkx=3.2.1=pyhd8ed1ab_0
  - numpy=1.26.4=py39h474f0d3_0
  - ocl-icd=2.3.2=hd590300_1
  - openssl=3.3.2=hb9d3cd8_0
  - packaging=24.1=pyhd8ed1ab_0
  - pip=24.2=pyh8b19718_1
  - propcache=0.2.0=py39h8cd3c5a_2
  - psutil=6.0.0=py39h8cd3c5a_2
  - pycparser=2.22=pyhd8ed1ab_0
  - pyg=2.6.1=py39_torch_2.4.0_cu124
  - pyparsing=3.2.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.20=h13acc7a_1_cpython
  - python_abi=3.9=5_cp39
  - pytorch=2.4.1=py3.9_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_6
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.1.2=py39_torch_2.4.0_cu124
  - pyyaml=6.0.2=py39h8cd3c5a_1
  - readline=8.2=h8228510_1
  - requests=2.32.3=pyhd8ed1ab_0
  - scipy=1.13.1=py39haf93ffa_0
  - setuptools=75.1.0=pyhd8ed1ab_0
  - stride=1.6.4=1
  - sympy=1.13.3=pyh2585a3b_104
  - tbb=2021.13.0=h84d6215_0
  - tk=8.6.13=noxft_h4845f30_101
  - torchtriton=3.0.0=py39
  - tqdm=4.66.5=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024b=hc8b5060_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.15.3=py39h8cd3c5a_0
  - zstandard=0.23.0=py39h08a7858_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - annotated-types==0.7.0
      - biopython==1.84
      - einops==0.8.0
      - mmtf-python==1.1.3
      - progres==0.2.7
      - pydantic==2.9.2
      - pydantic-core==2.23.4
```

**Comment by jgreener64** [comment]
Good to hear, and thanks for reporting the solution.
